### ISSUE TITLE
webapp file upload broken on non-german setups

### ISSUE THREAD

**Issue by sneumann** [nilshoffmann/jmzTab-m#2]
As seen during the hangout, in some cases the file upload "Durchsuchen" is not visible, 
and/or not responding to user clicks. Yours, Steffen

**Comment by nilshoffmann** [comment]
Reverted to standard file chooser dialog in https://github.com/nilshoffmann/jmzTab-m/commit/6377b0937167ed38ac95f12643b0ef0dbaa143ea

Tests look good, please check https://lifs.isas.de/mztabvalidator

**Comment by sneumann** [comment]
Yes, worksforme.
