### ISSUE TITLE
Confusing output: no errors / there were errors

### ISSUE THREAD

**Issue by sneumann** [nilshoffmann/jmzTab-m#7]
Hi, I am getting 
```
Begin check mztab file: /vol/R/BioC/devel/xcms/R/faahKO.mzTab
There exist errors in the metadata section or protein/peptide/small_molecule/small_molecule_feature/small_molecule_evidence header section! Validation will stop, and ignore data table check!
No errors in file:/vol/R/BioC/devel/xcms/R/faahKO.mzTab file!
There were errors while processing your file, please check the output for details!
Finish!
```
Only if I `-level Warn` then I see 
`[Warn-2041] line 88: The metadata section does not contain a small_molecule-identification_reliability parameter definition.`. Note that https://github.com/HUPO-PSI/mzTab/blob/master/specification_document/1_1_draft_specs/mzTab_format_specification_1_1-M_draft.adoc#6252-small_molecule-identification_reliability says `mandatory=False`.
Yours, Steffen

**Comment by nilshoffmann** [comment]
Please check whether the latest version fixes this behaviour for your file. If not, please reopen this issue and provide the file for testing, if possible.
